imagenet_classes = [
    'tench', 'goldfish', 'great white shark', 'tiger shark',
    'hammerhead shark', 'electric ray', 'stingray', 'rooster', 'hen',
    'ostrich', 'brambling', 'goldfinch', 'house finch', 'junco',
    'indigo bunting', 'American robin', 'bulbul', 'jay', 'magpie', 'chickadee',
    'American dipper', 'kite (bird of prey)', 'bald eagle', 'vulture',
    'great grey owl', 'fire salamander', 'smooth newt', 'newt',
    'spotted salamander', 'axolotl', 'American bullfrog', 'tree frog',
    'tailed frog', 'loggerhead sea turtle', 'leatherback sea turtle',
    'mud turtle', 'terrapin', 'box turtle', 'banded gecko', 'green iguana',
    'Carolina anole', 'desert grassland whiptail lizard', 'agama',
    'frilled-necked lizard', 'alligator lizard', 'Gila monster',
    'European green lizard', 'chameleon', 'Komodo dragon', 'Nile crocodile',
    'American alligator', 'triceratops', 'worm snake', 'ring-necked snake',
    'eastern hog-nosed snake', 'smooth green snake', 'kingsnake',
    'garter snake', 'water snake', 'vine snake', 'night snake',
    'boa constrictor', 'African rock python', 'Indian cobra', 'green mamba',
    'sea snake', 'Saharan horned viper', 'eastern diamondback rattlesnake',
    'sidewinder rattlesnake', 'trilobite', 'harvestman', 'scorpion',
    'yellow garden spider', 'barn spider', 'European garden spider',
    'southern black widow', 'tarantula', 'wolf spider', 'tick', 'centipede',
    'black grouse', 'ptarmigan', 'ruffed grouse', 'prairie grouse', 'peafowl',
    'quail', 'partridge', 'african grey parrot', 'macaw',
    'sulphur-crested cockatoo', 'lorikeet', 'coucal', 'bee eater', 'hornbill',
    'hummingbird', 'jacamar', 'toucan', 'duck', 'red-breasted merganser',
    'goose', 'black swan', 'tusker', 'echidna', 'platypus', 'wallaby', 'koala',
    'wombat', 'jellyfish', 'sea anemone', 'brain coral', 'flatworm',
    'nematode', 'conch', 'snail', 'slug', 'sea slug', 'chiton',
    'chambered nautilus', 'Dungeness crab', 'rock crab', 'fiddler crab',
    'red king crab', 'American lobster', 'spiny lobster', 'crayfish',
    'hermit crab', 'isopod', 'white stork', 'black stork', 'spoonbill',
    'flamingo', 'little blue heron', 'great egret', 'bittern bird',
    'crane bird', 'limpkin', 'common gallinule', 'American coot', 'bustard',
    'ruddy turnstone', 'dunlin', 'common redshank', 'dowitcher',
    'oystercatcher', 'pelican', 'king penguin', 'albatross', 'grey whale',
    'killer whale', 'dugong', 'sea lion', 'Chihuahua', 'Japanese Chin',
    'Maltese', 'Pekingese', 'Shih Tzu', 'King Charles Spaniel', 'Papillon',
    'toy terrier', 'Rhodesian Ridgeback', 'Afghan Hound', 'Basset Hound',
    'Beagle', 'Bloodhound', 'Bluetick Coonhound', 'Black and Tan Coonhound',
    'Treeing Walker Coonhound', 'English foxhound', 'Redbone Coonhound',
    'borzoi', 'Irish Wolfhound', 'Italian Greyhound', 'Whippet',
    'Ibizan Hound', 'Norwegian Elkhound', 'Otterhound', 'Saluki',
    'Scottish Deerhound', 'Weimaraner', 'Staffordshire Bull Terrier',
    'American Staffordshire Terrier', 'Bedlington Terrier', 'Border Terrier',
    'Kerry Blue Terrier', 'Irish Terrier', 'Norfolk Terrier',
    'Norwich Terrier', 'Yorkshire Terrier', 'Wire Fox Terrier',
    'Lakeland Terrier', 'Sealyham Terrier', 'Airedale Terrier',
    'Cairn Terrier', 'Australian Terrier', 'Dandie Dinmont Terrier',
    'Boston Terrier', 'Miniature Schnauzer', 'Giant Schnauzer',
    'Standard Schnauzer', 'Scottish Terrier', 'Tibetan Terrier',
    'Australian Silky Terrier', 'Soft-coated Wheaten Terrier',
    'West Highland White Terrier', 'Lhasa Apso', 'Flat-Coated Retriever',
    'Curly-coated Retriever', 'Golden Retriever', 'Labrador Retriever',
    'Chesapeake Bay Retriever', 'German Shorthaired Pointer', 'Vizsla',
    'English Setter', 'Irish Setter', 'Gordon Setter', 'Brittany dog',
    'Clumber Spaniel', 'English Springer Spaniel', 'Welsh Springer Spaniel',
    'Cocker Spaniel', 'Sussex Spaniel', 'Irish Water Spaniel', 'Kuvasz',
    'Schipperke', 'Groenendael dog', 'Malinois', 'Briard', 'Australian Kelpie',
    'Komondor', 'Old English Sheepdog', 'Shetland Sheepdog', 'collie',
    'Border Collie', 'Bouvier des Flandres dog', 'Rottweiler',
    'German Shepherd Dog', 'Dobermann', 'Miniature Pinscher',
    'Greater Swiss Mountain Dog', 'Bernese Mountain Dog',
    'Appenzeller Sennenhund', 'Entlebucher Sennenhund', 'Boxer', 'Bullmastiff',
    'Tibetan Mastiff', 'French Bulldog', 'Great Dane', 'St. Bernard', 'husky',
    'Alaskan Malamute', 'Siberian Husky', 'Dalmatian', 'Affenpinscher',
    'Basenji', 'pug', 'Leonberger', 'Newfoundland dog', 'Great Pyrenees dog',
    'Samoyed', 'Pomeranian', 'Chow Chow', 'Keeshond', 'brussels griffon',
    'Pembroke Welsh Corgi', 'Cardigan Welsh Corgi', 'Toy Poodle',
    'Miniature Poodle', 'Standard Poodle',
    'Mexican hairless dog (xoloitzcuintli)', 'grey wolf',
    'Alaskan tundra wolf', 'red wolf or maned wolf', 'coyote', 'dingo',
    'dhole', 'African wild dog', 'hyena', 'red fox', 'kit fox', 'Arctic fox',
    'grey fox', 'tabby cat', 'tiger cat', 'Persian cat', 'Siamese cat',
    'Egyptian Mau', 'cougar', 'lynx', 'leopard', 'snow leopard', 'jaguar',
    'lion', 'tiger', 'cheetah', 'brown bear', 'American black bear',
    'polar bear', 'sloth bear', 'mongoose', 'meerkat', 'tiger beetle',
    'ladybug', 'ground beetle', 'longhorn beetle', 'leaf beetle',
    'dung beetle', 'rhinoceros beetle', 'weevil', 'fly', 'bee', 'ant',
    'grasshopper', 'cricket insect', 'stick insect', 'cockroach',
    'praying mantis', 'cicada', 'leafhopper', 'lacewing', 'dragonfly',
    'damselfly', 'red admiral butterfly', 'ringlet butterfly',
    'monarch butterfly', 'small white butterfly', 'sulphur butterfly',
    'gossamer-winged butterfly', 'starfish', 'sea urchin', 'sea cucumber',
    'cottontail rabbit', 'hare', 'Angora rabbit', 'hamster', 'porcupine',
    'fox squirrel', 'marmot', 'beaver', 'guinea pig', 'common sorrel horse',
    'zebra', 'pig', 'wild boar', 'warthog', 'hippopotamus', 'ox',
    'water buffalo', 'bison', 'ram (adult male sheep)', 'bighorn sheep',
    'Alpine ibex', 'hartebeest', 'impala (antelope)', 'gazelle',
    'arabian camel', 'llama', 'weasel', 'mink', 'European polecat',
    'black-footed ferret', 'otter', 'skunk', 'badger', 'armadillo',
    'three-toed sloth', 'orangutan', 'gorilla', 'chimpanzee', 'gibbon',
    'siamang', 'guenon', 'patas monkey', 'baboon', 'macaque', 'langur',
    'black-and-white colobus', 'proboscis monkey', 'marmoset',
    'white-headed capuchin', 'howler monkey', 'titi monkey',
    "Geoffroy's spider monkey", 'common squirrel monkey', 'ring-tailed lemur',
    'indri', 'Asian elephant', 'African bush elephant', 'red panda',
    'giant panda', 'snoek fish', 'eel', 'silver salmon', 'rock beauty fish',
    'clownfish', 'sturgeon', 'gar fish', 'lionfish', 'pufferfish', 'abacus',
    'abaya', 'academic gown', 'accordion', 'acoustic guitar',
    'aircraft carrier', 'airliner', 'airship', 'altar', 'ambulance',
    'amphibious vehicle', 'analog clock', 'apiary', 'apron', 'trash can',
    'assault rifle', 'backpack', 'bakery', 'balance beam', 'balloon',
    'ballpoint pen', 'Band-Aid', 'banjo', 'baluster / handrail', 'barbell',
    'barber chair', 'barbershop', 'barn', 'barometer', 'barrel', 'wheelbarrow',
    'baseball', 'basketball', 'bassinet', 'bassoon', 'swimming cap',
    'bath towel', 'bathtub', 'station wagon', 'lighthouse', 'beaker',
    'military hat (bearskin or shako)', 'beer bottle', 'beer glass',
    'bell tower', 'baby bib', 'tandem bicycle', 'bikini', 'ring binder',
    'binoculars', 'birdhouse', 'boathouse', 'bobsleigh', 'bolo tie',
    'poke bonnet', 'bookcase', 'bookstore', 'bottle cap', 'hunting bow',
    'bow tie', 'brass memorial plaque', 'bra', 'breakwater', 'breastplate',
    'broom', 'bucket', 'buckle', 'bulletproof vest', 'high-speed train',
    'butcher shop', 'taxicab', 'cauldron', 'candle', 'cannon', 'canoe',
    'can opener', 'cardigan', 'car mirror', 'carousel', 'tool kit',
    'cardboard box / carton', 'car wheel', 'automated teller machine',
    'cassette', 'cassette player', 'castle', 'catamaran', 'CD player', 'cello',
    'mobile phone', 'chain', 'chain-link fence', 'chain mail', 'chainsaw',
    'storage chest', 'chiffonier', 'bell or wind chime', 'china cabinet',
    'Christmas stocking', 'church', 'movie theater', 'cleaver',
    'cliff dwelling', 'cloak', 'clogs', 'cocktail shaker', 'coffee mug',
    'coffeemaker', 'spiral or coil', 'combination lock', 'computer keyboard',
    'candy store', 'container ship', 'convertible', 'corkscrew', 'cornet',
    'cowboy boot', 'cowboy hat', 'cradle', 'construction crane',
    'crash helmet', 'crate', 'infant bed', 'Crock Pot', 'croquet ball',
    'crutch', 'cuirass', 'dam', 'desk', 'desktop computer',
    'rotary dial telephone', 'diaper', 'digital clock', 'digital watch',
    'dining table', 'dishcloth', 'dishwasher', 'disc brake', 'dock',
    'dog sled', 'dome', 'doormat', 'drilling rig', 'drum', 'drumstick',
    'dumbbell', 'Dutch oven', 'electric fan', 'electric guitar',
    'electric locomotive', 'entertainment center', 'envelope',
    'espresso machine', 'face powder', 'feather boa', 'filing cabinet',
    'fireboat', 'fire truck', 'fire screen', 'flagpole', 'flute',
    'folding chair', 'football helmet', 'forklift', 'fountain', 'fountain pen',
    'four-poster bed', 'freight car', 'French horn', 'frying pan', 'fur coat',
    'garbage truck', 'gas mask or respirator', 'gas pump', 'goblet', 'go-kart',
    'golf ball', 'golf cart', 'gondola', 'gong', 'gown', 'grand piano',
    'greenhouse', 'radiator grille', 'grocery store', 'guillotine',
    'hair clip', 'hair spray', 'half-track', 'hammer', 'hamper', 'hair dryer',
    'hand-held computer', 'handkerchief', 'hard disk drive', 'harmonica',
    'harp', 'combine harvester', 'hatchet', 'holster', 'home theater',
    'honeycomb', 'hook', 'hoop skirt', 'gymnastic horizontal bar',
    'horse-drawn vehicle', 'hourglass', 'iPod', 'clothes iron',
    'carved pumpkin', 'jeans', 'jeep', 'T-shirt', 'jigsaw puzzle', 'rickshaw',
    'joystick', 'kimono', 'knee pad', 'knot', 'lab coat', 'ladle', 'lampshade',
    'laptop computer', 'lawn mower', 'lens cap', 'letter opener', 'library',
    'lifeboat', 'lighter', 'limousine', 'ocean liner', 'lipstick',
    'slip-on shoe', 'lotion', 'music speaker', 'loupe magnifying glass',
    'sawmill', 'magnetic compass', 'messenger bag', 'mailbox', 'tights',
    'one-piece bathing suit', 'manhole cover', 'maraca', 'marimba', 'mask',
    'matchstick', 'maypole', 'maze', 'measuring cup', 'medicine cabinet',
    'megalith', 'microphone', 'microwave oven', 'military uniform', 'milk can',
    'minibus', 'miniskirt', 'minivan', 'missile', 'mitten', 'mixing bowl',
    'mobile home', 'ford model t', 'modem', 'monastery', 'monitor', 'moped',
    'mortar and pestle', 'graduation cap', 'mosque', 'mosquito net', 'vespa',
    'mountain bike', 'tent', 'computer mouse', 'mousetrap', 'moving van',
    'muzzle', 'metal nail', 'neck brace', 'necklace', 'baby pacifier',
    'notebook computer', 'obelisk', 'oboe', 'ocarina', 'odometer',
    'oil filter', 'pipe organ', 'oscilloscope', 'overskirt', 'bullock cart',
    'oxygen mask', 'product packet / packaging', 'paddle', 'paddle wheel',
    'padlock', 'paintbrush', 'pajamas', 'palace', 'pan flute', 'paper towel',
    'parachute', 'parallel bars', 'park bench', 'parking meter',
    'railroad car', 'patio', 'payphone', 'pedestal', 'pencil case',
    'pencil sharpener', 'perfume', 'Petri dish', 'photocopier', 'plectrum',
    'Pickelhaube', 'picket fence', 'pickup truck', 'pier', 'piggy bank',
    'pill bottle', 'pillow', 'ping-pong ball', 'pinwheel', 'pirate ship',
    'drink pitcher', 'block plane', 'planetarium', 'plastic bag', 'plate rack',
    'farm plow', 'plunger', 'Polaroid camera', 'pole', 'police van', 'poncho',
    'pool table', 'soda bottle', 'plant pot', "potter's wheel", 'power drill',
    'prayer rug', 'printer', 'prison', 'missile', 'projector', 'hockey puck',
    'punching bag', 'purse', 'quill', 'quilt', 'race car', 'racket',
    'radiator', 'radio', 'radio telescope', 'rain barrel',
    'recreational vehicle', 'fishing casting reel', 'reflex camera',
    'refrigerator', 'remote control', 'restaurant', 'revolver', 'rifle',
    'rocking chair', 'rotisserie', 'eraser', 'rugby ball',
    'ruler measuring stick', 'sneaker', 'safe', 'safety pin', 'salt shaker',
    'sandal', 'sarong', 'saxophone', 'scabbard', 'weighing scale',
    'school bus', 'schooner', 'scoreboard', 'CRT monitor', 'screw',
    'screwdriver', 'seat belt', 'sewing machine', 'shield', 'shoe store',
    'shoji screen / room divider', 'shopping basket', 'shopping cart',
    'shovel', 'shower cap', 'shower curtain', 'ski', 'balaclava ski mask',
    'sleeping bag', 'slide rule', 'sliding door', 'slot machine', 'snorkel',
    'snowmobile', 'snowplow', 'soap dispenser', 'soccer ball', 'sock',
    'solar thermal collector', 'sombrero', 'soup bowl', 'keyboard space bar',
    'space heater', 'space shuttle', 'spatula', 'motorboat', 'spider web',
    'spindle', 'sports car', 'spotlight', 'stage', 'steam locomotive',
    'through arch bridge', 'steel drum', 'stethoscope', 'scarf', 'stone wall',
    'stopwatch', 'stove', 'strainer', 'tram', 'stretcher', 'couch', 'stupa',
    'submarine', 'suit', 'sundial', 'sunglasses', 'sunglasses', 'sunscreen',
    'suspension bridge', 'mop', 'sweatshirt', 'swim trunks / shorts', 'swing',
    'electrical switch', 'syringe', 'table lamp', 'tank', 'tape player',
    'teapot', 'teddy bear', 'television', 'tennis ball', 'thatched roof',
    'front curtain', 'thimble', 'threshing machine', 'throne', 'tile roof',
    'toaster', 'tobacco shop', 'toilet seat', 'torch', 'totem pole',
    'tow truck', 'toy store', 'tractor', 'semi-trailer truck', 'tray',
    'trench coat', 'tricycle', 'trimaran', 'tripod', 'triumphal arch',
    'trolleybus', 'trombone', 'hot tub', 'turnstile', 'typewriter keyboard',
    'umbrella', 'unicycle', 'upright piano', 'vacuum cleaner', 'vase',
    'vaulted or arched ceiling', 'velvet fabric', 'vending machine',
    'vestment', 'viaduct', 'violin', 'volleyball', 'waffle iron', 'wall clock',
    'wallet', 'wardrobe', 'military aircraft', 'sink', 'washing machine',
    'water bottle', 'water jug', 'water tower', 'whiskey jug', 'whistle',
    'hair wig', 'window screen', 'window shade', 'Windsor tie', 'wine bottle',
    'airplane wing', 'wok', 'wooden spoon', 'wool', 'split-rail fence',
    'shipwreck', 'sailboat', 'yurt', 'website', 'comic book', 'crossword',
    'traffic or street sign', 'traffic light', 'dust jacket', 'menu', 'plate',
    'guacamole', 'consomme', 'hot pot', 'trifle', 'ice cream', 'popsicle',
    'baguette', 'bagel', 'pretzel', 'cheeseburger', 'hot dog',
    'mashed potatoes', 'cabbage', 'broccoli', 'cauliflower', 'zucchini',
    'spaghetti squash', 'acorn squash', 'butternut squash', 'cucumber',
    'artichoke', 'bell pepper', 'cardoon', 'mushroom', 'Granny Smith apple',
    'strawberry', 'orange', 'lemon', 'fig', 'pineapple', 'banana', 'jackfruit',
    'cherimoya (custard apple)', 'pomegranate', 'hay', 'carbonara',
    'chocolate syrup', 'dough', 'meatloaf', 'pizza', 'pot pie', 'burrito',
    'red wine', 'espresso', 'tea cup', 'eggnog', 'mountain', 'bubble', 'cliff',
    'coral reef', 'geyser', 'lakeshore', 'promontory', 'sandbar', 'beach',
    'valley', 'volcano', 'baseball player', 'bridegroom', 'scuba diver',
    'rapeseed', 'daisy', "yellow lady's slipper", 'corn', 'acorn', 'rose hip',
    'horse chestnut seed', 'coral fungus', 'agaric', 'gyromitra',
    'stinkhorn mushroom', 'earth star fungus', 'hen of the woods mushroom',
    'bolete', 'corn cob', 'toilet paper'
]

caltech_names = [
'rooster','chair','gramophone','pigeon','mayfly','cellphone','wild_cat','octopus','wheelchair','dollar_bill','minaret',
'Faces','electric_guitar','water_lilly','hawksbill','llama','watch','camera','binocular','ant','schooner','dalmatian','pizza','garfield','barrel','platypus',
'gerenuk','beaver','ceiling_fan','tick','nautilus','accordion','ibis','rhino','windsor_chair','saxophone','ferry','airplanes','strawberry','stegosaurus',
'lotus','stapler','ewer','inline_skate','Leopards','pyramid','starfish','cup','scissors','crocodile_head','butterfly','metronome','snoopy','okapi','panda','helicopter','cougar_body','headphone',
'crocodile','lobster','sunflower','menorah','Faces_easy','sea_horse','dolphin','car_side','crayfish','Motorbikes','revolver','crab','soccer_ball','ketch','flamingo_head','umbrella','grand_piano',
'BACKGROUND_Google','joshua_tree','pagoda','dragonfly','lamp','chandelier','bass','laptop','buddha','flamingo','anchor','scorpion','brontosaurus','elephant',
'hedgehog','stop_sign','kangaroo','brain','mandolin','emu','trilobite','yin_yang','cannon','euphonium','cougar_face','wrench','bonsai'
]

cub_names = [
'black footed albatross','laysan albatross','sooty albatross','groove billed ani','crested auklet','least auklet','parakeet auklet','rhinoceros auklet','brewer blackbird','red winged blackbird',
'rusty blackbird','yellow headed blackbird','bobolink','indigo bunting','lazuli bunting','painted bunting','cardinal','spotted catbird','gray catbird','yellow breasted chat','eastern towhee','chuck will widow',
'brandt cormorant','red faced cormorant','pelagic cormorant','bronzed cowbird','shiny cowbird','brown creeper','american crow','fish crow','black billed cuckoo','mangrove cuckoo','yellow billed cuckoo',
'gray crowned rosy finch','purple finch','northern flicker','acadian flycatcher','great crested flycatcher','least flycatcher','olive sided flycatcher','scissor tailed flycatcher','vermilion flycatcher',
'yellow bellied flycatcher','frigatebird','northern fulmar','gadwall','american goldfinch','european goldfinch','boat tailed grackle','eared grebe','horned grebe','pied billed grebe','western grebe','blue grosbeak',
'evening grosbeak','pine grosbeak','rose breasted grosbeak','pigeon guillemot','california gull','glaucous winged gull','heermann gull','herring gull','ivory gull','ring billed gull','slaty backed gull','western gull',
'anna hummingbird','ruby throated hummingbird','rufous hummingbird','green violetear','long tailed jaeger','pomarine jaeger','blue jay','florida jay','green jay','dark eyed junco','tropical kingbird','gray kingbird',
'belted kingfisher','green kingfisher','pied kingfisher','ringed kingfisher','white breasted kingfisher','red legged kittiwake','horned lark','pacific loon','mallard','western meadowlark','hooded merganser',
'red breasted merganser','mockingbird','nighthawk','clark nutcracker','white breasted nuthatch','baltimore oriole','hooded oriole','orchard oriole','scott oriole','ovenbird','brown pelican','white pelican','western wood pewee',
'sayornis','american pipit','whip poor will','horned puffin','common raven','white necked raven','american redstart','geococcyx','loggerhead shrike','great grey shrike','baird sparrow','black throated sparrow','brewer sparrow',
'chipping sparrow','clay colored sparrow','house sparrow','field sparrow','fox sparrow','grasshopper sparrow','harris sparrow','henslow sparrow','le conte sparrow','lincoln sparrow','nelson sharp tailed sparrow','savannah sparrow',
'seaside sparrow','song sparrow','tree sparrow','vesper sparrow','white crowned sparrow','white throated sparrow','cape glossy starling','bank swallow','barn swallow','cliff swallow','tree swallow','scarlet tanager','summer tanager',
'artic tern','black tern','caspian tern','common tern','elegant tern','forsters tern','least tern','green tailed towhee','brown thrasher','sage thrasher','black capped vireo','blue headed vireo','philadelphia vireo','red eyed vireo',
'warbling vireo','white eyed vireo','yellow throated vireo','bay breasted warbler','black and white warbler','black throated blue warbler','blue winged warbler','canada warbler','cape may warbler','cerulean warbler','chestnut sided warbler',
'golden winged warbler','hooded warbler','kentucky warbler','magnolia warbler','mourning warbler','myrtle warbler','nashville warbler','orange crowned warbler','palm warbler','pine warbler','prairie warbler','prothonotary warbler','swainson warbler',
'tennessee warbler','wilson warbler','worm eating warbler','yellow warbler','northern waterthrush','louisiana waterthrush','bohemian waxwing','cedar waxwing','american three toed woodpecker','pileated woodpecker','red bellied woodpecker',
'red cockaded woodpecker','red headed woodpecker','downy woodpecker','bewick wren','cactus wren','carolina wren','house wren','marsh wren','rock wren','winter wren','common yellowthroat'
]

food_names = ['Apple pie', 'Baby back ribs', 'Baklava', 'Beef carpaccio', 'Beef tartare', 'Beet salad', 'Beignets', 'Bibimbap', 'Bread pudding', 'Breakfast burrito', 'Bruschetta', 'Caesar salad', 'Cannoli', 'Caprese salad', 'Carrot cake', 'Ceviche', 'Cheesecake', 
'Cheese plate', 'Chicken curry', 'Chicken quesadilla', 'Chicken wings', 'Chocolate cake', 'Chocolate mousse', 'Churros', 'Clam chowder', 'Club sandwich', 'Crab cakes', 'Creme brulee', 'Croque madame', 'Cup cakes', 'Deviled eggs', 'Donuts', 'Dumplings', 
'Edamame', 'Eggs benedict', 'Escargots', 'Falafel', 'Filet mignon', 'Fish and chips', 'Foie gras', 'French fries', 'French onion soup', 'French toast', 'Fried calamari', 'Fried rice', 'Frozen yogurt', 'Garlic bread', 'Gnocchi', 'Greek salad', 'Grilled cheese sandwich', 
'Grilled salmon', 'Guacamole', 'Gyoza', 'Hamburger', 'Hot and sour soup', 'Hot dog', 'Huevos rancheros', 'Hummus', 'Ice cream', 'Lasagna', 'Lobster bisque', 'Lobster roll sandwich', 'Macaroni and cheese', 'Macarons', 'Miso soup', 'Mussels', 'Nachos', 'Omelette', 'Onion rings', 
'Oysters', 'Pad thai', 'Paella', 'Pancakes', 'Panna cotta', 'Peking duck', 'Pho', 'Pizza', 'Pork chop', 'Poutine', 'Prime rib', 'Pulled pork sandwich', 'Ramen', 'Ravioli', 'Red velvet cake', 'Risotto', 'Samosa', 'Sashimi', 'Scallops', 'Seaweed salad', 'Shrimp and grits', 'Spaghetti bolognese', 
'Spaghetti carbonara', 'Spring rolls', 'Steak', 'Strawberry shortcake', 'Sushi', 'Tacos', 'Takoyaki', 'Tiramisu', 'Tuna tartare', 'Waffles']

pet_names = [
    'abyssinian', 'american bulldog', 'american pit bull terrier', 'basset hound', 'beagle', 'birman',
    'bengal', 'bombay', 'boxer', 'british shorthair', 'chihuahua','english cocker spaniel', 'english setter', 'egyptian mau', 'great pyrenees', 'havanese', 'japanese chin',
    'keeshond', 'leonberger', 'maine coon', 'miniature pinscher', 'newfoundland', 'persian','pug', 'ragdoll', 'russian blue','samoyed', 'scottish terrier', 'siamese',
    'sphynx', 'staffordshire bull terrier', 'shiba inu','wheaten terrier', 'yorkshire terrier'
]

car_names = [
'am general hummer suv 2000','acura rl sedan 2012','acura tl sedan 2012','acura tl type-s 2008','acura tsx sedan 2012','acura integra type r 2001','acura zdx hatchback 2012','aston martin v8 vantage convertible 2012','aston martin v8 vantage coupe 2012','aston martin virage convertible 2012',
'aston martin virage coupe 2012','audi rs 4 convertible 2008','audi a5 coupe 2012','audi tts coupe 2012','audi r8 coupe 2012','audi v8 sedan 1994','audi 100 sedan 1994','audi 100 wagon 1994','audi tt hatchback 2011','audi s6 sedan 2011','audi s5 convertible 2012',
'audi s5 coupe 2012','audi s4 sedan 2012','audi s4 sedan 2007','audi tt rs coupe 2012','bmw activehybrid 5 sedan 2012','bmw 1 series convertible 2012','bmw 1 series coupe 2012','bmw 3 series sedan 2012','bmw 3 series wagon 2012','bmw 6 series convertible 2007',
'bmw x5 suv 2007','bmw x6 suv 2012','bmw m3 coupe 2012','bmw m5 sedan 2010','bmw m6 convertible 2010','bmw x3 suv 2012','bmw z4 convertible 2012','bentley continental supersports conv. convertible 2012','bentley arnage sedan 2009','bentley mulsanne sedan 2011',
'bentley continental gt coupe 2012','bentley continental gt coupe 2007','bentley continental flying spur sedan 2007','bugatti veyron 16.4 convertible 2009','bugatti veyron 16.4 coupe 2009','buick regal gs 2012','buick rainier suv 2007','buick verano sedan 2012',
'buick enclave suv 2012','cadillac cts-v sedan 2012','cadillac srx suv 2012','cadillac escalade ext crew cab 2007','chevrolet silverado 1500 hybrid crew cab 2012','chevrolet corvette convertible 2012','chevrolet corvette zr1 2012','chevrolet corvette ron fellows edition z06 2007',
'chevrolet traverse suv 2012','chevrolet camaro convertible 2012','chevrolet hhr ss 2010','chevrolet impala sedan 2007','chevrolet tahoe hybrid suv 2012','chevrolet sonic sedan 2012','chevrolet express cargo van 2007','chevrolet avalanche crew cab 2012','chevrolet cobalt ss 2010',
'chevrolet malibu hybrid sedan 2010','chevrolet trailblazer ss 2009','chevrolet silverado 2500hd regular cab 2012','chevrolet silverado 1500 classic extended cab 2007','chevrolet express van 2007','chevrolet monte carlo coupe 2007','chevrolet malibu sedan 2007','chevrolet silverado 1500 extended cab 2012',
'chevrolet silverado 1500 regular cab 2012','chrysler aspen suv 2009','chrysler sebring convertible 2010','chrysler town and country minivan 2012','chrysler 300 srt-8 2010','chrysler crossfire convertible 2008','chrysler pt cruiser convertible 2008','daewoo nubira wagon 2002','dodge caliber wagon 2012',
'dodge caliber wagon 2007','dodge caravan minivan 1997','dodge ram pickup 3500 crew cab 2010','dodge ram pickup 3500 quad cab 2009','dodge sprinter cargo van 2009','dodge journey suv 2012','dodge dakota crew cab 2010','dodge dakota club cab 2007','dodge magnum wagon 2008','dodge challenger srt8 2011',
'dodge durango suv 2012','dodge durango suv 2007','dodge charger sedan 2012','dodge charger srt-8 2009','eagle talon hatchback 1998','fiat 500 abarth 2012','fiat 500 convertible 2012','ferrari ff coupe 2012','ferrari california convertible 2012','ferrari 458 italia convertible 2012','ferrari 458 italia coupe 2012',
'fisker karma sedan 2012','ford f-450 super duty crew cab 2012','ford mustang convertible 2007','ford freestar minivan 2007','ford expedition el suv 2009','ford edge suv 2012','ford ranger supercab 2011','ford gt coupe 2006','ford f-150 regular cab 2012','ford f-150 regular cab 2007','ford focus sedan 2007',
'ford e-series wagon van 2012','ford fiesta sedan 2012','gmc terrain suv 2012','gmc savana van 2012','gmc yukon hybrid suv 2012','gmc acadia suv 2012','gmc canyon extended cab 2012','geo metro convertible 1993','hummer h3t crew cab 2010','hummer h2 sut crew cab 2009','honda odyssey minivan 2012',
'honda odyssey minivan 2007','honda accord coupe 2012','honda accord sedan 2012','hyundai veloster hatchback 2012','hyundai santa fe suv 2012','hyundai tucson suv 2012','hyundai veracruz suv 2012','hyundai sonata hybrid sedan 2012','hyundai elantra sedan 2007','hyundai accent sedan 2012','hyundai genesis sedan 2012',
'hyundai sonata sedan 2012','hyundai elantra touring hatchback 2012','hyundai azera sedan 2012','infiniti g coupe ipl 2012','infiniti qx56 suv 2011','isuzu ascender suv 2008','jaguar xk xkr 2012','jeep patriot suv 2012','jeep wrangler suv 2012','jeep liberty suv 2012','jeep grand cherokee suv 2012','jeep compass suv 2012',
'lamborghini reventon coupe 2008','lamborghini aventador coupe 2012','lamborghini gallardo lp 570-4 superleggera 2012','lamborghini diablo coupe 2001','land rover range rover suv 2012','land rover lr2 suv 2012','lincoln town car sedan 2011','mini cooper roadster convertible 2012','maybach landaulet convertible 2012',
'mazda tribute suv 2011','mclaren mp4-12c coupe 2012','mercedes-benz 300-class convertible 1993','mercedes-benz c-class sedan 2012','mercedes-benz sl-class coupe 2009','mercedes-benz e-class sedan 2012','mercedes-benz s-class sedan 2012','mercedes-benz sprinter van 2012','mitsubishi lancer sedan 2012','nissan leaf hatchback 2012',
'nissan nv passenger van 2012','nissan juke hatchback 2012','nissan 240sx coupe 1998','plymouth neon coupe 1999','porsche panamera sedan 2012','ram c/v cargo van minivan 2012','rolls-royce phantom drophead coupe convertible 2012','rolls-royce ghost sedan 2012','rolls-royce phantom sedan 2012','scion xd hatchback 2012',
'spyker c8 convertible 2009','spyker c8 coupe 2009','suzuki aerio sedan 2007','suzuki kizashi sedan 2012','suzuki sx4 hatchback 2012','suzuki sx4 sedan 2012','tesla model s sedan 2012','toyota sequoia suv 2012','toyota camry sedan 2012','toyota corolla sedan 2012','toyota 4runner suv 2012','volkswagen golf hatchback 2012',
'volkswagen golf hatchback 1991','volkswagen beetle hatchback 2012','volvo c30 hatchback 2012','volvo 240 sedan 1993','volvo xc90 suv 2007','smart fortwo convertible 2012'
]

dtd_names = [
'banded','blotchy','braided','bubbly','bumpy','chequered','cobwebbed','cracked','crosshatched','crystalline','dotted','fibrous','flecked','freckled','frilly','gauzy','grid','grooved','honeycombed','interlaced','knitted','lacelike','lined','marbled','matted','meshed','paisley','perforated','pitted','pleated','polka-dotted','porous','potholed','scaly','smeared',
'spiralled','sprinkled','stained','stratified','striped','studded','swirly','veined','waffled','woven','wrinkled','zigzagged']

places_names = [
    "airfield", "airplane_cabin", "airport_terminal", "alcove", "alley",
    "amphitheater", "amusement_arcade", "amusement_park", "apartment_building",
    "aquarium", "aqueduct", "arcade", "arch", "archaelogical_excavation", "archive",
    "arena", "army_base", "art_gallery", "art_school", "art_studio", "artists_loft",
    "assembly_line", "athletic_field", "atrium", "attic", "auditorium", "auto_factory",
    "auto_showroom", "badlands", "bakery", "balcony", "ball_pit", "ballroom",
    "bamboo_forest", "bank_vault", "banquet_hall", "bar", "barn", "barndoor",
    "baseball_field", "basement", "basketball_court", "bathroom", "bazaar", "beach",
    "beach_house", "beauty_salon", "bedchamber", "bedroom", "beer_garden", "beer_hall",
    "berth", "biology_laboratory", "boardwalk", "boat_deck", "boathouse", "bookstore",
    "booth", "botanical_garden", "bow_window", "bowling_alley", "boxing_ring", "bridge",
    "building_facade", "bullring", "burial_chamber", "bus_interior", "bus_station",
    "butchers_shop", "butte", "cabin", "cafeteria", "campsite", "campus", "canal",
    "candy_store", "canyon", "car_interior", "carrousel", "castle", "catacomb",
    "cemetery", "chalet", "chemistry_lab", "childs_room", "church", "classroom",
    "clean_room", "cliff", "closet", "clothing_store", "coast", "cockpit", "coffee_shop",
    "computer_room", "conference_center", "conference_room", "construction_site", "corn_field",
    "corral", "corridor", "cottage", "courthouse", "courtyard", "creek", "crevasse",
    "crosswalk", "dam", "delicatessen", "department_store", "desert", "diner",
    "dining_hall", "dining_room", "discotheque", "doorway", "dorm_room", "downtown",
    "dressing_room", "driveway", "drugstore", "elevator", "embassy", "engine_room",
    "entrance_hall", "escalator", "excavation", "fabric_store", "farm", "fastfood_restaurant",
    "field", "fire_escape", "fire_station", "fishpond", "flea_market", "florist_shop",
    "food_court", "football_field", "forest", "forest_path", "forest_road", "formal_garden",
    "fountain", "galley", "garage", "gas_station", "gazebo", "general_store", "gift_shop",
    "glacier", "golf_course", "greenhouse", "grotto", "gymnasium", "hangar", "harbor",
    "hardware_store", "hayfield", "heliport", "highway", "home_office", "home_theater",
    "hospital", "hospital_room", "hot_spring", "hotel", "house", "hunting_lodge",
    "ice_cream_parlor", "ice_floe", "iceberg", "igloo", "industrial_area", "inn",
    "jacuzzi", "jail_cell", "japanese_garden", "jewelry_shop", "junkyard", "kasbah",
    "kennel", "kindergarten_classroom", "kitchen", "lagoon", "lake", "landfill",
    "landing_deck", "laundromat", "lawn", "lecture_room", "legislative_chamber",
    "library", "lighthouse", "living_room", "loading_dock", "lobby", "lock_chamber",
    "locker_room", "mansion", "manufactured_home", "market", "marsh", "martial_arts_gym",
    "mausoleum", "medina", "mezzanine", "mosque", "motel", "mountain", "movie_theater",
    "museum", "music_studio", "natural_history_museum", "nursery", "nursing_home",
    "oast_house", "ocean", "office", "office_building", "office_cubicles", "oilrig",
    "operating_room", "orchard", "orchestra_pit", "pagoda", "palace", "pantry",
    "park", "parking_garage", "parking_lot", "pasture", "patio", "pavilion", "pet_shop",
    "pharmacy", "phone_booth", "physics_laboratory", "picnic_area", "pier", "pizzeria",
    "playground", "playroom", "plaza", "pond", "porch", "promenade", "pub", "racecourse",
    "raceway", "raft", "railroad_track", "rainforest", "reception", "recreation_room",
    "repair_shop", "residential_neighborhood", "restaurant", "restaurant_kitchen",
    "restaurant_patio", "rice_paddy", "river", "rock_arch", "roof_garden", "rope_bridge",
    "ruin", "runway", "sandbox", "sauna", "schoolhouse", "science_museum", "server_room",
    "shed", "shoe_shop", "shopfront", "shopping_mall", "shower", "ski_resort", "ski_slope",
    "sky", "skyscraper", "slum", "snowfield", "soccer_field", "stable", "stadium",
    "stage", "staircase", "storage_room", "street", "subway_station", "supermarket",
    "sushi_bar", "swamp", "swimming_hole", "swimming_pool", "synagogue", "television_room",
    "television_studio", "temple", "throne_room", "ticket_booth", "topiary_garden", "tower",
    "toyshop", "train_interior", "train_station", "tree_farm", "tree_house", "trench",
    "tundra", "underwater", "utility_room", "valley", "vegetable_garden", "veterinarians_office",
    "viaduct", "village", "vineyard", "volcano", "volleyball_court", "waiting_room",
    "water_park", "water_tower", "waterfall", "watering_hole", "wave", "wet_bar",
    "wheat_field", "wind_farm", "windmill", "yard", "youth_hostel", "zen_garden"
]